AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para el Frontend en React

Resources:
  # Bucket S3 para el código del frontend
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: frontend-deployment-bucket
      AccessControl: PublicRead

  # Bucket Policy para el acceso público
  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub '${FrontendS3Bucket.Arn}/*'

  # Distribución de CloudFront para el frontend
  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendS3Bucket.DomainName
            Id: FrontendOrigin
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        DefaultRootObject: index.html
